-- Starter questions (15 per category)
insert into public.questions (text, category, weight, active) values
  ('What small win from today made you smile?', 'playful', 1, true),
  ('Which song reminds you most of us right now?', 'playful', 1, true),
  ('If we could teleport for dinner, where would we go?', 'playful', 1, true),
  ('What is a silly inside joke you want to create this week?', 'playful', 1, true),
  ('Which emoji captures your mood about us today?', 'playful', 1, true),
  ('What flavor ice cream should represent our duo?', 'playful', 1, true),
  ('What mini adventure should we try this weekend?', 'playful', 2, true),
  ('What game should we play together soon?', 'playful', 1, true),
  ('What outfit of mine do you want to borrow for fun?', 'playful', 1, true),
  ('What meme would you send me right now?', 'playful', 1, true),
  ('If our day was a movie genre, what would it be?', 'playful', 1, true),
  ('What new nickname should we test drive?', 'playful', 1, true),
  ('What snack should always be stocked for our next hangout?', 'playful', 1, true),
  ('Which fictional couple are we channeling today?', 'playful', 1, true),
  ('What spontaneous dance move should we learn together?', 'playful', 1, true),

  ('What value did you live out most strongly today?', 'values', 1, true),
  ('Where do you feel we are most in sync right now?', 'values', 1, true),
  ('How can we support each others personal growth this week?', 'values', 2, true),
  ('What boundary are you proud we maintain?', 'values', 1, true),
  ('Which shared ritual means the most to you lately?', 'values', 1, true),
  ('Where could we practice more gratitude together?', 'values', 1, true),
  ('What does being a good partner look like for you today?', 'values', 1, true),
  ('Which of our goals feel closest to reality?', 'values', 1, true),
  ('What promise do you want to recommit to?', 'values', 1, true),
  ('Where do you feel the safest with me?', 'values', 1, true),
  ('How can I show love in your preferred language tomorrow?', 'values', 1, true),
  ('What is one generous act you want us to do soon?', 'values', 1, true),
  ('What tradition do you dream of starting for our future?', 'values', 1, true),
  ('Where can we simplify life together this month?', 'values', 1, true),
  ('What personal win can we celebrate together today?', 'values', 1, true),

  ('Which memory of us felt like pure magic?', 'memories', 1, true),
  ('What was our funniest miscommunication?', 'memories', 1, true),
  ('What song instantly takes you back to an early moment?', 'memories', 1, true),
  ('When did you first know we were a great team?', 'memories', 1, true),
  ('What simple routine of ours do you treasure?', 'memories', 1, true),
  ('Which trip would you relive exactly as it happened?', 'memories', 1, true),
  ('What unexpected gesture of mine meant a lot to you?', 'memories', 1, true),
  ('What has been your favorite cozy night in?', 'memories', 1, true),
  ('What was a moment you felt especially seen by me?', 'memories', 1, true),
  ('Which of our milestones deserves a commemorative plant?', 'memories', 1, true),
  ('What was the most delicious meal we ever shared?', 'memories', 1, true),
  ('What first impression of me turned out wrong?', 'memories', 1, true),
  ('What is a photo of us you never want to delete?', 'memories', 1, true),
  ('When did we tackle a challenge better than expected?', 'memories', 1, true),
  ('What random conversation with me still makes you grin?', 'memories', 1, true),

  ('What goal should we take one tiny step toward this week?', 'goals', 1, true),
  ('What part of our shared future excites you most tonight?', 'goals', 1, true),
  ('Where could we invest more time or energy together?', 'goals', 1, true),
  ('What skill would you love us to learn side by side?', 'goals', 1, true),
  ('How do you picture our ideal morning routine in a year?', 'goals', 1, true),
  ('What financial habit should we tune up together?', 'goals', 1, true),
  ('What wellness ritual could we start together soon?', 'goals', 1, true),
  ('What dream trip feels within reach now?', 'goals', 1, true),
  ('What shared risk are you willing to take with me?', 'goals', 1, true),
  ('What milestone should we celebrate early?', 'goals', 1, true),
  ('How can we carve out deeper focus time for us?', 'goals', 1, true),
  ('What future memory are you excited to create next month?', 'goals', 1, true),
  ('Where can we ask for help to accelerate a dream?', 'goals', 1, true),
  ('What habit should we retire to make room for joy?', 'goals', 1, true),
  ('What does success as a couple mean to you right now?', 'goals', 1, true);

-- Pet species catalog
insert into public.pet_species (name, rarity, base_growth_rate) values
  ('Lumen Fox', 'common', 3),
  ('Misty Bun', 'common', 3),
  ('Solar Puffin', 'common', 2),
  ('Willow Lynx', 'rare', 2),
  ('Nebula Pup', 'rare', 2),
  ('Aurora Koi', 'rare', 1),
  ('Stardust Fawn', 'ultra', 1),
  ('Celeste Drake', 'ultra', 1),
  ('Bloom Chameleon', 'common', 3),
  ('Echo Sprite', 'rare', 2);

-- Mission templates
insert into public.missions (code, period, objective) values
  ('D_WATER_3', 'daily', '{"type":"water","count":3}'),
  ('D_CHECKIN_2', 'daily', '{"type":"question_answer","count":2}'),
  ('D_FEED_PET', 'daily', '{"type":"pet_feed","count":1}'),
  ('D_WB_CREATE', 'daily', '{"type":"whiteboard_session","count":1}'),
  ('W_HARVEST_10', 'weekly', '{"type":"harvest","count":10}'),
  ('W_RANDOM_VISIT', 'weekly', '{"type":"random_event","count":1}'),
  ('W_GARDEN_REFRESH', 'weekly', '{"type":"plant","count":6}'),
  ('W_GIFT_PARTNER', 'weekly', '{"type":"send_gift","count":1}'),
  ('M_EVOLVE_PET', 'monthly', '{"type":"pet_stage","target":"teen"}'),
  ('M_COMPLETE_20', 'monthly', '{"type":"mission_complete","count":20}');
