name: supabase

on:
  pull_request:
    paths:
      - 'supabase/**'
  push:
    branches: [main]
    paths:
      - 'supabase/**'

jobs:
  lint:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Lint migrations
        run: pnpm dlx supabase@latest db lint
  dry-run:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - name: Validate migrations (dry run)
        run: pnpm dlx supabase@latest db push --dry-run
